on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
        description: "yarn workspace name"
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      VSCE_PAT:
        required: true
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        type: string
        description: "yarn workspace name"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
            #container: ubuntu:18.04
          #- os: ubuntu-20.04
          #  target: aarch64-unknown-linux-gnu
          #  code-target: linux-arm64
          #- os: ubuntu-20.04
          #  target: arm-unknown-linux-gnueabihf
          #  code-target: linux-armhf
          - os: macos-11
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-11
            target: aarch64-apple-darwin
            code-target: darwin-arm64
    uses: ./.github/workflows/execute-yarn-workspace-command.yml
    with:
      workspace: ${{ inputs.workspace }}
      command: build
      os: ${{ matrix.os }}
      target: ${{ matrix.target }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
          