name: Manual CD

on:
  workflow_dispatch:
    inputs:
      from:
        description: 'From commit'
        required: true
        type: string
      since:
        description: 'Since commit'
        required: true
        type: string

jobs:
  setup:
    uses: ./.github/workflows/detect-workspace-changes.yml
    with:
      from: ${{ github.sha }}
      since: ${{ inputs.since }}
  
  publish-libraries:
    if : ${{ needs.setup.outputs.libraries != '[]' && github.ref_name == 'main' }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.libraries)}}
    uses: ./.github/workflows/publish-library.yml
    with:
      workspace: ${{ matrix.workspace.name }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}


  
  publish-core:
    if: ${{ needs.setup.outputs.extensions != '[]' && github.ref_name == 'main' }}
    needs: 
      - setup
      - publish-libraries
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.extensions)}}
    uses: ./.github/workflows/publish-core.yml
    with:
      workspace: ${{ matrix.workspace.name }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

  publish-extensions:
    if : ${{ needs.setup.outputs.extensions != '[]' }}
    needs: 
      - setup
      - publish-libraries
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.extensions)}}
    uses: ./.github/workflows/publish-extension-auto.yml
    with:
      workspace: ${{ matrix.workspace.name }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}