name: Publish library

on:
  workflow_call:
    inputs:
      workspace: 
        required: true
        type: string
        description: |
          The yarn workspace the library is in.
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      VSCE_PAT:
        required: true
  workflow_dispatch:
    inputs:
      workspace:
        description: |
          The yarn workspace the library is in.
        required: true
        type: string

jobs:
  publish:
    uses: ./.github/workflows/execute-yarn-workspace-command.yml
    with:
      workspace: ${{ inputs.workspace }}
      command: publish
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
        